version: "3"

services:
  mailhog:
    image:
      mailhog/mailhog
    container_name:
      mailhog
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      - MH_STORAGE=maildir # memory / mongodb / maildir
      - MH_MAILDIR_PATH=/mail-volume
    volumes:
      - mailhog-volume:/mail-volume
volumes:
  mailhog-volume:
